// Mock OpenAI-compatible server for testing the repo-wiki pipeline offline.
// Returns a plan JSON for the planning prompt, markdown for page prompts.
// Usage: node test/mock-llm.js  (listens on http://127.0.0.1:8688/v1)
//        MOCK_DELAY_MS=1000 node test/mock-llm.js   # simulate slow model
const http = require('http');
const DELAY = parseInt(process.env.MOCK_DELAY_MS, 10) || 0;

const PLAN = JSON.stringify({
  pages: [
    { path: 'overview.md', title: 'Project Overview', description: 'What the project does', files: ['README.md', 'package.json'] },
    { path: 'architecture/core.md', title: 'Core Architecture', description: 'Main module', files: ['src/app.js', 'src/util.js', 'src/DOES-NOT-EXIST.js'] },
  ],
});

const server = http.createServer((req, res) => {
  let body = '';
  req.on('data', c => { body += c; });
  req.on('end', () => {
    if (!req.url.endsWith('/chat/completions')) {
      res.writeHead(404); res.end('not found'); return;
    }
    const payload = JSON.parse(body);
    const userMsg = payload.messages.filter(m => m.role === 'user').map(m => m.content).join('\n');
    let content;
    if (userMsg.includes('Return ONLY a JSON object')) {
      content = 'Here is the plan:\n```json\n' + PLAN + '\n```';
    } else {
      const m = userMsg.match(/Write the wiki page "([^"]+)"/);
      const title = m ? m[1] : 'Page';
      content = `# ${title}\n\nGenerated by mock model \`${payload.model}\`.\n\n\`\`\`mermaid\ngraph TD\n  A[Repo] --> B[Wiki]\n\`\`\`\n\nThis page documents the repository based on the attached sources.\n`;
    }
    res.writeHead(200, { 'content-type': 'application/json' });
    const reply = JSON.stringify({ choices: [{ message: { role: 'assistant', content } }] });
    setTimeout(() => res.end(reply), DELAY);
  });
});
server.listen(8688, '127.0.0.1', () => console.log('mock LLM on http://127.0.0.1:8688/v1'));
