#!/usr/bin/env node
/**
 * Wiki -> PDF exporter (PDF export feature of open-repo-wiki)
 * Renders every .md file from a wiki content folder (e.g. one generated by
 * generate.js, or Qoder's repowiki) into a styled PDF (GitHub-like theme,
 * syntax highlighting, rendered mermaid diagrams), preserving the folder
 * hierarchy. Also writes standalone .html previews.
 *
 * Usage: node export.js [sourceDir] [outDir]
 */
const fs = require('fs');
const path = require('path');

function resolvePlaywright() {
  try { return require('playwright'); } catch { /* handled below */ }
  console.error('playwright not found. Install the PDF export dependencies with: npm install');
  process.exit(1);
}
const { chromium } = resolvePlaywright();

function resolvePdfLib() {
  try { return require('pdf-lib'); } catch { /* handled below */ }
  console.error('pdf-lib not found. Install the PDF export dependencies with: npm install');
  process.exit(1);
}

// Default source: the Qoder repowiki of the current working directory.
// Resolve to absolute paths — file:// URLs used for rendering require them.
const SRC = path.resolve(process.argv[2] || path.join(process.cwd(), '.qoder/repowiki/en/content'));
const OUT = path.resolve(process.argv[3] || path.join(process.cwd(), 'wiki-pdf'));
const COMPLETE_NAME = '00-COMPLETE-WIKI.pdf';

if (!fs.existsSync(SRC)) {
  console.error(`Source not found: ${SRC}`);
  console.error('Generate the wiki in Qoder first (Repo Wiki), or pass the content dir as the first argument.');
  process.exit(1);
}

function walk(dir) {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walk(full));
    else if (entry.name.endsWith('.md')) files.push(full);
  }
  return files;
}

function htmlTemplate(title, markdown) {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${title.replace(/</g, '&lt;')}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/github-markdown-css@5/github-markdown-light.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@11/styles/github.min.css">
<script src="https://cdn.jsdelivr.net/npm/marked@12/marked.min.js"><\/script>
<script src="https://cdn.jsdelivr.net/npm/highlight.js@11/lib/common.min.js"><\/script>
<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"><\/script>
<style>
  body { margin: 0; background: #fff; }
  .markdown-body { box-sizing: border-box; max-width: 900px; margin: 0 auto; padding: 32px 40px; }
  .mermaid { text-align: center; margin: 16px 0; }
  .mermaid svg { max-width: 100%; height: auto; }
  pre { white-space: pre-wrap; word-wrap: break-word; }
  cite { display: block; background: #f6f8fa; border: 1px solid #d0d7de; border-radius: 6px;
         padding: 8px 12px; margin: 0 0 16px; font-style: normal; font-size: 13px; }
  @media print {
    .markdown-body { max-width: none; padding: 0; }
    h1, h2, h3 { break-after: avoid; }
    pre, .mermaid, table { break-inside: avoid; }
  }
</style>
</head>
<body>
<article class="markdown-body" id="content"></article>
<script>
  const md = ${JSON.stringify(markdown)};
  const renderer = new marked.Renderer();
  const origCode = renderer.code.bind(renderer);
  renderer.code = function (code, lang) {
    if (lang === 'mermaid') {
      return '<div class="mermaid">' + code.replace(/</g, '&lt;') + '</div>';
    }
    return origCode(code, lang);
  };
  marked.setOptions({
    renderer,
    highlight: (code, lang) => {
      try {
        return lang && hljs.getLanguage(lang)
          ? hljs.highlight(code, { language: lang }).value
          : hljs.highlightAuto(code).value;
      } catch (e) { return code; }
    },
    gfm: true
  });
  document.getElementById('content').innerHTML = marked.parse(md);
  document.querySelectorAll('pre code').forEach(el => { try { hljs.highlightElement(el); } catch (e) {} });
  mermaid.initialize({ startOnLoad: false, theme: 'neutral', securityLevel: 'loose' });
  mermaid.run({ querySelector: '.mermaid' })
    .catch(err => console.warn('mermaid:', err && err.message))
    .finally(() => { window.__renderDone = true; });
<\/script>
</body>
</html>`;
}

(async () => {
  // The generator's root index.md is navigation source only; we emit index.html
  // ourselves from the catalog, so skip it here to avoid an overwrite collision.
  const files = walk(SRC).filter(f => path.relative(SRC, f) !== 'index.md').sort();
  console.log(`Found ${files.length} markdown files`);
  fs.mkdirSync(OUT, { recursive: true });

  const browser = await chromium.launch();
  const page = await browser.newPage();

  let ok = 0, failed = 0;
  const indexEntries = [];
  const failedRels = [];

  for (const file of files) {
    const rel = path.relative(SRC, file);
    const outPdf = path.join(OUT, rel.replace(/\.md$/, '.pdf'));
    const outHtml = path.join(OUT, rel.replace(/\.md$/, '.html'));
    fs.mkdirSync(path.dirname(outPdf), { recursive: true });

    const title = path.basename(file, '.md');
    const markdown = fs.readFileSync(file, 'utf8');
    const html = htmlTemplate(title, markdown);

    const tmpHtml = outHtml + '.tmp.html';
    const tmpPdf = outPdf + '.tmp.pdf';
    try {
      // page.setContent produced blank single-page PDFs; loading via file:// works.
      // Render into temp files and swap in on success, so a failed doc keeps
      // its previous HTML/PDF from the last successful run.
      fs.writeFileSync(tmpHtml, html);
      await page.goto('file://' + encodeURI(tmpHtml), { waitUntil: 'networkidle', timeout: 60000 });
      await page.waitForFunction('window.__renderDone === true', { timeout: 30000 });
      await page.waitForTimeout(150);
      await page.pdf({
        path: tmpPdf,
        format: 'A4',
        printBackground: true,
        margin: { top: '18mm', bottom: '18mm', left: '14mm', right: '14mm' },
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate:
          `<div style="width:100%;font-size:8px;color:#999;padding:0 14mm;display:flex;justify-content:space-between;">` +
          `<span>${title.replace(/</g, '&lt;')}</span>` +
          `<span><span class="pageNumber"></span> / <span class="totalPages"></span></span></div>`,
      });
      fs.renameSync(tmpHtml, outHtml);
      fs.renameSync(tmpPdf, outPdf);
      indexEntries.push(rel.replace(/\.md$/, ''));
      ok++;
      console.log(`  OK  ${rel}`);
    } catch (err) {
      failed++;
      failedRels.push(rel.replace(/\.md$/, ''));
      for (const f of [tmpHtml, tmpPdf]) { if (fs.existsSync(f)) fs.unlinkSync(f); }
      console.error(`FAIL  ${rel}: ${err.message.split('\n')[0]}`);
    }
  }

  // --- Remove stale outputs (docs renamed/deleted in the wiki since last run) ---
  // Failed docs keep their previous output; with a manifest from an earlier run,
  // only files this script generated are eligible for deletion, so anything
  // placed in the output folder by hand is left alone.
  const expected = new Set();
  for (const rel of [...indexEntries, ...failedRels]) {
    expected.add(path.join(OUT, rel + '.pdf'));
    expected.add(path.join(OUT, rel + '.html'));
  }
  expected.add(path.join(OUT, 'index.html'));
  expected.add(path.join(OUT, COMPLETE_NAME));
  const manifestPath = path.join(OUT, '.manifest.json');
  let owned = null; // null -> no manifest yet (older runs): treat every pdf/html as ours
  try {
    owned = new Set(JSON.parse(fs.readFileSync(manifestPath, 'utf8')).map(r => path.join(OUT, r)));
  } catch { /* first run with manifest support */ }
  const walkOut = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walkOut(full);
        if (fs.readdirSync(full).length === 0) fs.rmdirSync(full);
      } else if (/\.(pdf|html)$/.test(entry.name) && !expected.has(full) && (!owned || owned.has(full))) {
        fs.unlinkSync(full);
        console.log(`  removed stale: ${path.relative(OUT, full)}`);
      }
    }
  };
  walkOut(OUT);

  // --- Merge everything into one central PDF with a table of contents ---
  console.log('\nBuilding combined PDF...');
  const { PDFDocument } = resolvePdfLib();
  const body = await PDFDocument.create();
  const tocEntries = [];
  let pageNo = 1;
  for (const rel of indexEntries) {
    const bytes = fs.readFileSync(path.join(OUT, rel + '.pdf'));
    const src = await PDFDocument.load(bytes);
    const pages = await body.copyPages(src, src.getPageIndices());
    pages.forEach(pg => body.addPage(pg));
    tocEntries.push({ title: rel, page: pageNo });
    pageNo += src.getPageCount();
  }

  // Render the TOC through the same browser for a matching look.
  // Rendered iteratively: entries are offset by the TOC's own page count so
  // the listed numbers match the physical pages of the final PDF.
  const projectName = path.basename(path.resolve(SRC, '../../..')) === '.qoder'
    ? path.basename(path.resolve(SRC, '../../../..'))
    : path.basename(path.dirname(OUT));
  const tocHtmlPath = path.join(OUT, '_toc.html');
  const tocPdfPath = path.join(OUT, '_toc.pdf');
  const renderToc = async (offset) => {
    const tocRows = tocEntries
      .map(e => `<tr><td style="padding:3px 8px 3px 0;">${e.title.replace(/</g, '&lt;').replace(/\//g, ' / ')}</td>` +
                `<td style="text-align:right;color:#57606a;white-space:nowrap;">${e.page + offset}</td></tr>`)
      .join('\n');
    const tocHtml = `<!DOCTYPE html><html><head><meta charset="utf-8">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/github-markdown-css@5/github-markdown-light.min.css">
<style>body{margin:0}.markdown-body{max-width:900px;margin:0 auto;padding:32px 40px}
table{width:100%;border-collapse:collapse;font-size:12px}</style></head>
<body><article class="markdown-body">
<h1>${projectName.replace(/</g, '&lt;')} — Wiki Documentation</h1>
<p>Generated ${new Date().toISOString().slice(0, 10)} · ${tocEntries.length} documents · ${pageNo - 1 + offset} pages</p>
<h2>Contents</h2>
<table>${tocRows}</table>
<p style="color:#57606a;font-size:11px;">Page numbers match the physical page position within this PDF (contents pages included).</p>
</article></body></html>`;
    fs.writeFileSync(tocHtmlPath, tocHtml);
    await page.goto('file://' + encodeURI(tocHtmlPath), { waitUntil: 'networkidle', timeout: 60000 });
    await page.pdf({
      path: tocPdfPath,
      format: 'A4',
      printBackground: true,
      margin: { top: '18mm', bottom: '18mm', left: '14mm', right: '14mm' },
    });
    return PDFDocument.load(fs.readFileSync(tocPdfPath));
  };
  let tocOffset = 0;
  let tocDoc = await renderToc(tocOffset);
  for (let i = 0; i < 3 && tocDoc.getPageCount() !== tocOffset; i++) {
    tocOffset = tocDoc.getPageCount();
    tocDoc = await renderToc(tocOffset);
  }

  const finalDoc = await PDFDocument.create();
  (await finalDoc.copyPages(tocDoc, tocDoc.getPageIndices())).forEach(pg => finalDoc.addPage(pg));
  (await finalDoc.copyPages(body, body.getPageIndices())).forEach(pg => finalDoc.addPage(pg));
  finalDoc.setTitle(`${projectName} — Wiki Documentation`);
  fs.writeFileSync(path.join(OUT, COMPLETE_NAME), await finalDoc.save());
  fs.unlinkSync(tocHtmlPath);
  fs.unlinkSync(tocPdfPath);
  console.log(`Combined PDF: ${path.join(OUT, COMPLETE_NAME)} (${finalDoc.getPageCount()} pages)`);

  await browser.close();

  const rendered = new Set(indexEntries);
  const escHtml = (s) => String(s).replace(/</g, '&lt;');
  const dirOfRel = (p) => { const i = p.lastIndexOf('/'); return i === -1 ? '' : p.slice(0, i); };
  const htmlLink = (title, relPath) => {
    const rel = relPath.replace(/\.md$/, '');
    const pdf = rendered.has(rel) ? ` &nbsp;<a href="${encodeURI(rel)}.pdf">[pdf]</a>` : '';
    return `<a href="${encodeURI(rel)}.html">${escHtml(title)}</a>${pdf}`;
  };

  // Prefer a nested, titled navigation built from the generator's catalog.json;
  // fall back to a flat list (e.g. when exporting a Qoder repowiki that has none).
  let navHtml;
  let catalog = null;
  try { catalog = JSON.parse(fs.readFileSync(path.join(SRC, '..', 'meta', 'catalog.json'), 'utf8')); } catch { /* no catalog */ }
  if (catalog && Array.isArray(catalog.pages)) {
    const pages = catalog.pages.filter(p => p.path && p.path !== 'index.md');
    const byDir = new Map();
    for (const p of pages) { const d = dirOfRel(p.path); if (!byDir.has(d)) byDir.set(d, []); byDir.get(d).push(p); }
    const items = [];
    for (const p of (byDir.get('') || [])) items.push(`<li>${htmlLink(p.title, p.path)}</li>`);
    for (const d of [...byDir.keys()].filter(Boolean).sort()) {
      const group = byDir.get(d);
      const landing = group.find(p => p.isLanding);
      const children = group.filter(p => !p.isLanding);
      const head = landing ? htmlLink(landing.title, landing.path) : `<strong>${escHtml(d)}</strong>`;
      const kids = children.map(c => `<li>${htmlLink(c.title, c.path)}</li>`).join('');
      items.push(`<li>${head}<ul>${kids}</ul></li>`);
    }
    navHtml = `<ul>${items.join('\n')}</ul>`;
  } else {
    navHtml = `<ul>${indexEntries
      .map(rel => `<li><a href="${encodeURI(rel)}.html">${escHtml(rel)}</a> &nbsp;<a href="${encodeURI(rel)}.pdf">[pdf]</a></li>`)
      .join('\n')}</ul>`;
  }
  fs.writeFileSync(
    path.join(OUT, 'index.html'),
    `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${projectName.replace(/</g, '&lt;')} — Wiki Export</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/github-markdown-css@5/github-markdown-light.min.css">
<style>body{margin:0}.markdown-body{max-width:900px;margin:0 auto;padding:32px 40px}</style></head>
<body><article class="markdown-body"><h1>Wiki Export</h1><p><a href=\"${COMPLETE_NAME}\"><strong>Complete wiki (single PDF)</strong></a></p>${navHtml}</article></body></html>`
  );

  // Record what we own so the next run only deletes files generated here
  fs.writeFileSync(manifestPath, JSON.stringify(
    [...expected].filter(f => fs.existsSync(f)).map(f => path.relative(OUT, f)).sort(), null, 2
  ));

  console.log(`\nDone: ${ok} exported, ${failed} failed -> ${OUT}`);
  process.exit(failed > 0 ? 1 : 0);
})();
